import { JobPipelineItem } from './types';

export const jobItems: JobPipelineItem[] = [
  {
    id: 1,
    company: 'Vercel',
    jobTitle: 'Frontend Engineer',
    status: 'Applied',
    nextAction: 'Send tailored portfolio intro',
    location: 'Remote',
  },
  {
    id: 2,
    company: 'Stripe',
    jobTitle: 'Product Engineer',
    status: 'Interview',
    nextAction: 'Prepare architecture walkthrough',
    location: 'San Francisco',
  },
  {
    id: 3,
    company: 'Notion',
    jobTitle: 'Platform UI Engineer',
    status: 'Offer',
    nextAction: 'Evaluate compensation package',
    location: 'New York',
  },
  {
    id: 4,
    company: 'Figma',
    jobTitle: 'Design Technologist',
    status: 'Rejected',
    nextAction: 'Request recruiter feedback',
    location: 'Remote',
  },
  {
    id: 5,
    company: 'OpenAI',
    jobTitle: 'Solutions Engineer',
    status: 'Applied',
    nextAction: 'Follow up with hiring lead',
    location: 'San Francisco',
  },
  {
    id: 6,
    company: 'Linear',
    jobTitle: 'Growth Engineer',
    status: 'Interview',
    nextAction: 'Practice product narrative',
    location: 'Remote',
  },
  {
    id: 7,
    company: 'Ramp',
    jobTitle: 'Fullstack Engineer',
    status: 'Offer',
    nextAction: 'Finalize start date window',
    location: 'New York',
  },
  {
    id: 8,
    company: 'Datadog',
    jobTitle: 'Developer Advocate',
    status: 'Rejected',
    nextAction: 'Archive notes for reapply cycle',
    location: 'Boston',
  },
];
